default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://pguser:pgpass@localhost:5432/rails_dev

test:
  <<: *default
  url: postgres://pguser:pgpass@localhost:5432/rails_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
